### ISSUE TITLE
Documentation: development instructions issue

### ISSUE THREAD

**Issue by OzarkShepherd** [gramps-project/gramps-webapi#183]
I was playing with this last night in a VM avoiding Docker and ran into some issues.
1. In Ubuntu 20.04, the apt package is gramps, not python3-gramps
2. the Ubuntu 20.04 package for gramps is 5.1.2, which threw a lot of gtk errors and wouldn't run in cli on a server that has no gui.  The error was "Unable to init server: Could not connect: Connection refused".  Even with python3-icu installed, the 5.1.3 deb installed through dpkg gives the same error on a 20.04 server without a gui.
`scott@testing:~$ gramps -i testing.gramps
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(gramps:4615): Gtk-WARNING **: 13:21:35.908: cannot open display: 
scott@testing:~$ 
`
Same with the following commands
gramps -O testing.gramps
gramps
I also tried installing xauth and xvfb but that didn't help either.
Perhaps a note could be added to the dev instructions that a GUI is needed or some workaround.
3. At the end in Running the app, should that be a python3 command instead of python?

**Comment by OzarkShepherd** [comment]
In the development instructions, option 2 for building a wheel for gramps 5.2 in a virtual environment, I ran into the following error:

> (gramps_webapi) scott@testing:~/gramps$ python3 setup.py bdist_wheel
> running bdist_wheel
> running build
> sh: 1: msgfmt: not found
> error: [Errno 2] No such file or directory: 'build/mo/ar/LC_MESSAGES/gramps.mo'

**Comment by DavidMStraub** [comment]
Hi,

> sh: 1: msgfmt: not found

`sudo apt install gettext`.

> Unable to init server: Could not connect: Connection refused

This is a warning the Gramps GUI code throws but the API runs nevertheless. It also runs in Docker without a display.

For the Docker image, I also had issues with Ubuntu (don't remember which), so I used Debian eventually. You can look at the Dockerfiles to see how to install everything from a pristine Debian:

https://github.com/DavidMStraub/gramps-docker/blob/master/Dockerfile
https://github.com/gramps-project/gramps-webapi/blob/master/Dockerfile

**Comment by OzarkShepherd** [comment]
Hello, 
Thanks for the response.  Installing gettext in Ubuntu 20.04 server, removing the gramps directory in the virtual environment, and starting over made some progress but still failed at `python3 setup.py bdist_wheel` with 
> Compiling data/gramps.xml.in >> build/data/gramps.xml
> msgfmt: cannot locate ITS rules for data/gramps.appdata.xml.in
> ERROR: build/data/gramps.appdata.xml was not merged into the translation files!

However, installing appstream resolved that error.  

The reason I was trying to run Gramps in CLI was that I was trying to get Gramps with CLI in the virtual machine that I was using for the webapi to import the database I had exported in XML format from the computer I normally use.  I must have done something wrong, because the xml came out as a .gramps file instead of sqlite and the webapi couldn't find the Gramps database.  Come to think of it, it might be helpful to have a document on how to export the Gramps database between computers for the webapi.

Even though I prefer Debian for my personal computer right now, I use Ubuntu 20.04 on my server with apache2 and a CA-issued certificate.  Since I already have various things set up on that server, I was hoping to figure out the webapi for Ubuntu so I wouldn't have to make major changes to everything else I have.  If I do figure something out, would you like a writeup on it?

**Comment by DavidMStraub** [comment]
Thanks, a write-up would be great!

Why not just use Docker (on Ubuntu)?

The installation of Gramps via pip is currently a bit tedious, but as soon as 5.2 is realeased, it should be as simple as `pip install gramps`, as I have contributed an automated wheel build and PyPI deployment ([here](https://github.com/gramps-project/gramps/blob/master/.travis.yml#L140-L146)).

Concerning export: actually, you don't have to export anything, just copy your Gramps database directory (or just the directory of the tree you need). In my case, I'm just `rsync`-ing the Gramp DB dir to my server everytime I change something.

**Comment by DavidMStraub** [comment]
> Concerning export: actually, you don't have to export anything, just copy your Gramps database directory (or just the directory of the tree you need). In my case, I'm just rsync-ing the Gramp DB dir to my server everytime I change something.

That of course assumes that the DB is already SQLite (note BSDDB), but that only has advantages anyway.

**Comment by DavidMStraub** [comment]
@OzarkShepherd FYI I'm now also struggling with pip-installing Gramps on Ubuntu as part of #185. After installing `msgfmt`, `gettext`, and `appstream`, I am currently failing here:

https://github.com/gramps-project/gramps-webapi/pull/185/checks?check_run_id=3039885674#step:5:143

```
  Compiling data/gramps.xml.in >> build/data/gramps.xml
  msgfmt: cannot locate ITS rules for data/gramps.appdata.xml.in
  ERROR: build/data/gramps.appdata.xml was not merged into the translation files!
```

Are you running into this as well? @Nick-Hall, any clue how to fix it?

**Comment by DavidMStraub** [comment]
Ah, I suspect its an issue that is fixed by the two new `its` files in your PR here https://github.com/gramps-project/gramps/pull/1241/files?

**Comment by OzarkShepherd** [comment]
Honestly, I don't remember what dependencies I installed before installing gettext and appstream, which resolved the error about gramps.appdata.xml for me.  I still have that VM, but it is messy regarding the packages so I don't use it anymore.  I'm not sure posting the apt list of installed packages would be very useful from that VM.  

I do have gramps (apt package) and gramps-webapi running in another VM, but ran into an unrelated problem with connecting Gramps.js to gramps-webapi, which is mentioned in #184 

My problem in problem 2 of this issue was getting the database recognized by gramps and gramps-webapi, which was resolved by putting the entire grampsdb directory into the VM with sftp and verified to work by running `gramps -l` after gramps was installed.  The other two problems in this Issue #183 are simple Doc recommendations, so you can close this Issue when you want.

**Comment by Nick-Hall** [comment]
Yes.  I copied the ITS rules into the Gramps distribution because I couldn't find a package where they were consistently available.

**Comment by DavidMStraub** [comment]
I improved the deployment instructions (using docker): https://gramps-project.github.io/gramps-webapi/Deployment/. I think this issue can be closed.
